# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh Baiad
description: > # this means to ignore newlines until "baseurl:"
  research developer @ aqr
repository: https://github.com/wemake-services/jekyll-theme-hackcss
url: www.joshbaiad.com  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Josh Baiad
email: josh@joshbaiad.com

navigation:
  - text: About
    url: /
  - text: Blog
    url: /blog
  - text: Projects
    url: /projects

projects:
  - name: onTREND Trading Platform
    description: Application for market signal research and day-to-day trading operations at the onTREND Fund of Spartan Fund Management Inc.
    link: /ontrend 
    image: /images/spartan_funds.jpeg
    caption: freelance
  - name: Visually Indicated Music
    description: Automatic soundtrack generation for animation and film with modern machine learning, computer vision, and signal processing methods.
    link: /visually-indicated-music
    image: /images/visually_indicated_music.png
    caption: thesis @ cmu
  - name: Risk Modeling
    description: Risk quantification for a given asset, strategy, or portfolio using stochastic models and market signals.
    link: /risk-modeling
    image: /images/aqr.png
    caption: internship
  - name: Captions
    description: Real-time, large-vocabulary speech recognition for Google Glass.
    link: /captions
    image: /images/captions.png
    caption: internship

social:
  - service: github
    username: jbaiad
    link: https://github.com/jbaiad
  - service: twitter
    username: joshbaiad
    link: https://twitter.com/joshbaiad

# Plugins
gems:
  - jekyll-seo-tag
